# Generated by Django 3.0.3 on 2020-02-16 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=60)),
                ('pwd', models.CharField(max_length=300)),
                ('writeDate', models.DateField(default=datetime.datetime(2020, 2, 16, 17, 22, 17, 750827))),
                ('hit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
