# Generated by Django 3.0.3 on 2020-02-16 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writeDate',
            field=models.DateField(default=datetime.datetime(2020, 2, 16, 8, 28, 34, 546731, tzinfo=utc)),
        ),
    ]
