# Generated by Django 3.0.3 on 2020-02-16 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200216_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writeDate',
            field=models.DateField(default=datetime.datetime(2020, 2, 16, 8, 29, 52, 718194, tzinfo=utc)),
        ),
    ]
