# Generated by Django 3.0.3 on 2020-02-16 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200216_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writeDate',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 16, 8, 30, 14, 409856, tzinfo=utc)),
        ),
    ]
