# Generated by Django 3.0.3 on 2020-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200216_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writeDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
