# Generated by Django 3.0.3 on 2020-02-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200216_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='writeDate',
            field=models.DateField(),
        ),
    ]
